import 'package:flutter/foundation.dart' show immutable;

/// 举报支持邮箱。以后要改地址,只改这一处。
const String kSupportEmail = 'support@laresapp.org';

/// 举报分类。审核员会实测这个列表,分类要覆盖 1.2 常见滥用类型。
///
/// **只存标识,不带任何给人看的文案。** 给人看的名字是会翻译的,
/// 一旦挂在枚举上就等于把 UI 依赖塞进了模型层,而且这里拿不到 context。
/// 显示名查表放在 UI 层:见 `ui/moderation_menus.dart` 的 `reportReasonLabel`。
enum ReportReason {
  harassment,
  hateSpeech,
  sexualContent,
  violence,
  illegal,
  spam,
  other;

  /// 给机器看的稳定标识。邮件正文、以后的服务端上报都用它 ——
  /// **绝不能**换成翻译后的文本,否则换个语言存量数据就对不上了。
  String get wire => name;

  /// 工单里给人读的英文名。
  ///
  /// 为什么不直接用 [wire] 了事:`hateSpeech`、`sexualContent` 这种驼峰名
  /// 机器好认、人读着别扭,而这封邮件是 App Store 审核员实测举报通道时
  /// **唯一会看到的东西**(指南 1.2 必查项)。
  ///
  /// 为什么不用界面上那套本地化文案:这是模型层,拿不到 BuildContext;
  /// 而且工单不该跟着举报人的界面语言变 —— 完整理由见 [buildReportBody]。
  /// 它与 UI 层的 `reportReasonLabel` 是两条独立的路,各自服务不同读者。
  ///
  /// 所以正文里两者并列,前者可检索、后者可阅读:
  ///   `Reason: hateSpeech (Hate speech or discrimination)`
  String get englishLabel => switch (this) {
    ReportReason.harassment => 'Harassment or personal attacks',
    ReportReason.hateSpeech => 'Hate speech or discrimination',
    ReportReason.sexualContent => 'Sexual or suggestive content',
    ReportReason.violence => 'Violence or graphic content',
    ReportReason.illegal => 'Illegal or dangerous activity',
    ReportReason.spam => 'Spam or flooding',
    ReportReason.other => 'Other',
  };
}

/// 一次举报的全部内容。构造出来就不再改,直接交给 [buildReportBody] 渲染。
@immutable
class ReportDraft {
  const ReportDraft({
    required this.targetUserId,
    required this.targetName,
    required this.circleId,
    required this.timestamp,
    required this.reason,
    required this.note,
    required this.reporterUserId,
    this.messageId,
    this.messageExcerpt,
  });

  /// 被举报者的稳定身份(userId,昵称随时会改,追责只能认这个)
  final String targetUserId;

  /// 举报当时对方的昵称,只是给人看的上下文
  final String targetName;

  final String circleId;

  final DateTime timestamp;

  final ReportReason reason;

  /// 举报人补充的自由文本,可以为空
  final String note;

  /// 举报具体某条消息时才有;举报「这个人」时为 null
  final String? messageId;

  /// 违规文本的短摘录,用 [excerptForReport] 生成
  final String? messageExcerpt;

  final String reporterUserId;
}

/// 邮件主题。
///
/// 分类用 [ReportReason.wire](稳定枚举名)而**不是**翻译后的显示名 ——
/// 见 [buildReportBody] 上的长注释。
String buildReportSubject(ReportDraft d) =>
    '[Lares Report] ${d.reason.wire} · ${d.targetUserId}';

/// 邮件正文(纯文本)。
///
/// **这份正文刻意不跟随界面语言,字段名与分类一律用稳定标识。** 三条理由:
///  1. 它是**给处理举报的人和以后的服务端解析器看的工单**,不是界面。
///     同一个字段在中文机上叫「举报理由分类」、在英文机上叫别的,
///     收件箱里就没法统一检索,存量邮件也会随 App 改版对不上。
///  2. 这里是模型层,**拿不到 BuildContext**,而把 context 传进来
///     会把 UI 依赖渗进业务代码(见 docs/l10n-guide.md)。
///  3. 商店主语言是 English,审核员实测举报流程时收到的正文得是他读得懂的。
///
/// 用户自己写的内容(昵称、补充说明、消息摘录)当然原样保留,不翻译也不改写。
/// 没有消息上下文时,消息相关的两行整行省掉,不留空标签。
String buildReportBody(ReportDraft d) {
  final lines = <String>[
    'Auto-generated by Lares. Please do not edit.',
    '',
    'Reported user ID: ${d.targetUserId}',
    'Reported user name: ${d.targetName}',
    'Circle ID: ${d.circleId}',
    'Reported at: ${d.timestamp.toUtc().toIso8601String()}',
    'Reason: ${d.reason.wire} (${d.reason.englishLabel})',
  ];
  final messageId = d.messageId;
  if (messageId != null && messageId.isNotEmpty) {
    lines.add('Message ID: $messageId');
  }
  final excerpt = d.messageExcerpt;
  if (excerpt != null && excerpt.trim().isNotEmpty) {
    lines.add('Message excerpt: $excerpt');
  }
  lines.addAll([
    'Note: ${d.note.trim().isEmpty ? '(none)' : d.note.trim()}',
    'Reporter ID: ${d.reporterUserId}',
    '',
    'We will resolve this report within 24 hours and reply to this address.',
  ]);
  return lines.join('\n');
}

/// 截取一小段违规文本放进举报里。
///
/// 按 **runes** 截而不是按 code unit:中文和 emoji 在 UTF-16 里占两个 code unit,
/// 按 code unit 切会把代理对劈成两半,邮件里就是一串乱码。
/// (ZWJ 组合 emoji 如「👨‍👩‍👧」仍可能从中间断开,但至少每个码点都是完整的,
/// 不会产生非法字符 —— 举报摘录只求可读,不值得为此引依赖。)
///
/// null 或纯空白返回 `''`。
String excerptForReport(String? text, {int maxChars = 200}) {
  if (text == null) return '';
  final trimmed = text.trim();
  if (trimmed.isEmpty) return '';
  final runes = trimmed.runes.toList();
  if (runes.length <= maxChars) return trimmed;
  return '${String.fromCharCodes(runes.take(maxChars))}…';
}

/// 组一个 mailto: 链接。编码交给 SDK 处理,别自己拼 %XX。
Uri buildReportMailtoUri(ReportDraft d) => Uri(
      scheme: 'mailto',
      path: kSupportEmail,
      queryParameters: <String, String>{
        'subject': buildReportSubject(d),
        'body': buildReportBody(d),
      },
    );
